# Generated by Django 4.2.1 on 2023-05-13 03:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0005_alter_movie_director"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="directed_by",
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_date",
            field=models.DateField(
                default=datetime.date(2023, 5, 13),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 13))
                ],
            ),
        ),
    ]
