# Generated by Django 4.2.1 on 2023-05-14 17:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0008_remove_actor_movieslist_remove_movie_actorlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="movies",
        ),
        migrations.RemoveField(
            model_name="director",
            name="movie",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="movieapi.actor"),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movieapi.director",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="dob",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 14))
                ]
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="dob",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 14))
                ]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_date",
            field=models.DateField(
                default=datetime.date(2023, 5, 14),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 14))
                ],
            ),
        ),
    ]
