# Generated by Django 4.2.1 on 2023-05-15 00:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0011_alter_movie_duration_alter_movie_metascore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 5, 15),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 15))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 5, 15),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 15))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_date",
            field=models.DateField(
                default=datetime.date(2023, 5, 15),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 5, 15))
                ],
            ),
        ),
    ]
