# Generated by Django 4.2.1 on 2023-05-15 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0012_alter_actor_dob_alter_director_dob_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ratedmovies",
            old_name="userRating",
            new_name="user_rating",
        ),
    ]
