# Generated by Django 4.2.1 on 2023-05-15 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0013_rename_userrating_ratedmovies_user_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
    ]
