# Generated by Django 4.2.1 on 2023-06-18 15:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0017_alter_actor_dob_alter_director_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 6, 18),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 18))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 6, 18),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 18))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_date",
            field=models.DateField(
                default=datetime.date(2023, 6, 18),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 18))
                ],
            ),
        ),
    ]
