# Generated by Django 4.2.1 on 2023-05-12 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_book_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="year",
        ),
        migrations.AddField(
            model_name="book",
            name="date_added",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="book",
            name="images",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
