# Generated by Django 4.2.1 on 2023-05-12 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_character_name_characters_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
    ]
