# Generated by Django 4.2.1 on 2023-05-12 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_characters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characters",
            old_name="character_name",
            new_name="name",
        ),
    ]
