# Generated by Django 4.2.1 on 2023-05-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_characters_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="app.book",
            ),
        ),
    ]
