# Generated by Django 4.2.1 on 2023-05-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0015_customuser_is_admin_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
