# Generated by Django 4.2.1 on 2023-06-08 00:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapi", "0016_remove_customuser_is_admin_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 6, 8),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 8))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="dob",
            field=models.DateField(
                default=datetime.date(2023, 6, 8),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 8))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="published_date",
            field=models.DateField(
                default=datetime.date(2023, 6, 8),
                validators=[
                    django.core.validators.MaxValueValidator(datetime.date(2023, 6, 8))
                ],
            ),
        ),
    ]
